/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

class BookTest {
    @Test void testBookConstructor() {
        Book book = new Book("1984", "George Orwell", 1949);
    
        assertEquals("1984", book.title());
        assertEquals("George Orwell", book.author());
        assertEquals(1949, book.yearPublished());
    }
}